language: swift
osx_image: xcode10

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
script:
  - set -o pipefail
  - xcodebuild -project Keychain.xcodeproj -scheme "Keychain-iOS" -sdk iphonesimulator clean build test
